name: hackathon_tuwaiq
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  qr_flutter: ^4.1.0
  supabase_flutter: ^1.10.25
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_barcode_scanner: ^2.0.0
  intl:
#  mobile_scanner: ^3.5.5
#  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - .env